# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy mobipetcare

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: create mobipetcare.tar
        run: |
          cd ./mobipetcare
          tar -cvf mobipetcare.tar *
          mv mobipetcare.tar ..
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "mobipetcare.tar"
          target: "/home/slawek/Application"
      - name: unpack and deploy application files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: rm -rf /home/slawek/Application/fe/mobipetcare/* && tar -xf /home/slawek/Application/mobipetcare.tar -C /home/slawek/Application/fe/mobipetcare/ && rm /home/slawek/Application/mobipetcare.tar
