# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy application

on:
  push:
    branches:
      - master
  workflow_dispatch:   
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.7]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run buildProdRpi
    - name: create deploy.tar
      run: |
        cd ./dist/accountant-client/
        tar -cvf deploy.tar *    
        mv deploy.tar ../..
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "deploy.tar"
        target: "/home/slawek/Application"
    - name: unpack and deploy application files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: rm -rf /home/slawek/Application/fe/angular-fe/* && tar -xf /home/slawek/Application/deploy.tar -C /home/slawek/Application/fe/angular-fe/
